title: title in _config.yml
author: EM@G
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  blog site em@g

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  coolgk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
